
[2019-07-24 10:35:18] Traceback (most recent call last):
  File "kivy\properties.pyx", line 860, in kivy.properties.ObservableDict.__getattr__
KeyError: 'scr_mngr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Jeandre Botha/Google Drive/UP/COS301/Interfaces_v2/main.py", line 68, in <module>
    LoginApp().run()
  File "D:\ProgramData\Anaconda3\lib\site-packages\kivy\app.py", line 855, in run
    runTouchApp()
  File "D:\ProgramData\Anaconda3\lib\site-packages\kivy\base.py", line 504, in runTouchApp
    EventLoop.window.mainloop()
  File "D:\ProgramData\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
    self._mainloop()
  File "D:\ProgramData\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
    EventLoop.idle()
  File "D:\ProgramData\Anaconda3\lib\site-packages\kivy\base.py", line 342, in idle
    self.dispatch_input()
  File "D:\ProgramData\Anaconda3\lib\site-packages\kivy\base.py", line 327, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\ProgramData\Anaconda3\lib\site-packages\kivy\base.py", line 293, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "C:\Users\Jeandre Botha\Google Drive\UP\COS301\Interfaces_v2\kivymd\list.py", line 411, in on_touch_up
    super(BaseListItem, self).on_touch_up(touch)
  File "C:\Users\Jeandre Botha\Google Drive\UP\COS301\Interfaces_v2\kivymd\ripplebehavior.py", line 68, in on_touch_up
    return super(CommonRipple, self).on_touch_up(touch)
  File "D:\ProgramData\Anaconda3\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1098, in kivy._event.EventObservers._dispatch
  File "D:\ProgramData\Anaconda3\lib\site-packages\kivy\lang\builder.py", line 64, in custom_callback
    exec(__kvlang__.co_value, idmap)
  File "C:\Users\Jeandre Botha\Google Drive\UP\COS301\Interfaces_v2\home.kv", line 42, in <module>
    on_release: app.root.get_screen('home').ids.scr_mngr.current = 'user_window'
  File "kivy\properties.pyx", line 863, in kivy.properties.ObservableDict.__getattr__
AttributeError: 'super' object has no attribute '__getattr__'


[2019-08-16 09:22:57] Traceback (most recent call last):
  File "F:/Documents/UP/COS301/capstone/Defendr/src/Interfaces_v2/main.py", line 100, in <module>
    LoginApp().run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\app.py", line 829, in run
    root = self.build()
  File "F:/Documents/UP/COS301/capstone/Defendr/src/Interfaces_v2/main.py", line 46, in build
    self.cef.Initialize()
AttributeError: 'LoginApp' object has no attribute 'cef'


[2019-08-16 09:26:19] Traceback (most recent call last):
  File "F:/Documents/UP/COS301/capstone/Defendr/src/Interfaces_v2/main.py", line 99, in <module>
    LoginApp().run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\app.py", line 855, in run
    runTouchApp()
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\base.py", line 504, in runTouchApp
    EventLoop.window.mainloop()
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
    self._mainloop()
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
    EventLoop.idle()
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\base.py", line 342, in idle
    self.dispatch_input()
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\base.py", line 327, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\base.py", line 293, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "F:\Documents\UP\COS301\capstone\Defendr\src\Interfaces_v2\kivymd\list.py", line 411, in on_touch_up
    super(BaseListItem, self).on_touch_up(touch)
  File "F:\Documents\UP\COS301\capstone\Defendr\src\Interfaces_v2\kivymd\ripplebehavior.py", line 68, in on_touch_up
    return super(CommonRipple, self).on_touch_up(touch)
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1098, in kivy._event.EventObservers._dispatch
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\lang\builder.py", line 64, in custom_callback
    exec(__kvlang__.co_value, idmap)
  File "F:\Documents\UP\COS301\capstone\Defendr\src\Interfaces_v2\nav_drawer.kv", line 18, in <module>
    on_release: app.load_website('https://www.google.com/','System Metrics')
  File "F:/Documents/UP/COS301/capstone/Defendr/src/Interfaces_v2/main.py", line 87, in load_website
    self.chromium.CreateBrowserSync(url=web_url,
AttributeError: 'bool' object has no attribute 'CreateBrowserSync'


<<<<<<< HEAD
[2019-08-24 14:26:49] Traceback (most recent call last):
  File "C:/Users/Chris/OneDrive/tuks/COS 301/capstone/Git/Defendr2/Defendr/src/Interfaces_v2/main.py", line 29, in <module>
    class LoginApp(App):
  File "C:/Users/Chris/OneDrive/tuks/COS 301/capstone/Git/Defendr2/Defendr/src/Interfaces_v2/main.py", line 44, in LoginApp
    Metrics.start()
NameError: name 'Metrics' is not defined


[2019-08-29 10:15:30] Traceback (most recent call last):
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 700, in _apply_rule
    setattr(widget_set, key, value)
  File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
  File "kivy\properties.pyx", line 497, in kivy.properties.Property.__set__
  File "kivy\properties.pyx", line 544, in kivy.properties.Property.set
  File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
  File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1096, in kivy._event.EventObservers._dispatch
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 73, in call_fn
    e_value = eval(value, idmap)
  File "<string>", line 13, in <module>
KeyError: 'Next Page'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Chris/OneDrive/tuks/COS 301/capstone/Git/Defendr2/Defendr/src/Interfaces_v2/main.py", line 98, in <module>
    LoginApp().run()
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\app.py", line 829, in run
    root = self.build()
  File "C:/Users/Chris/OneDrive/tuks/COS 301/capstone/Git/Defendr2/Defendr/src/Interfaces_v2/main.py", line 57, in build
    self.manager.add_widget(Logs_Window(name='logs_window'))
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\relativelayout.py", line 265, in __init__
    super(RelativeLayout, self).__init__(**kw)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\floatlayout.py", line 65, in __init__
    super(FloatLayout, self).__init__(**kwargs)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
    super(Layout, self).__init__(**kwargs)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\widget.py", line 361, in __init__
    rule_children=rule_children)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\widget.py", line 469, in apply_class_lang_rules
    rule_children=rule_children)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 538, in apply
    rule_children=rule_children)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 707, in _apply_rule
    e), cause=tb)
kivy.lang.builder.BuilderException: Parser: File "C:\Users\Chris\OneDrive\tuks\COS 301\capstone\Git\Defendr2\Defendr\src\Interfaces_v2\logs_window.kv", line 50:
...
     48:                    size_hint_x: None
     49:                    width: '50dp'
>>   50:                    icon: 'Next Page'
     51:                    on_press: root.next_pages(log_table)
     52:            BoxLayout:
...
KeyError: 'Next Page'
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 700, in _apply_rule
    setattr(widget_set, key, value)
  File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
  File "kivy\properties.pyx", line 497, in kivy.properties.Property.__set__
  File "kivy\properties.pyx", line 544, in kivy.properties.Property.set
  File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
  File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1096, in kivy._event.EventObservers._dispatch
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 73, in call_fn
    e_value = eval(value, idmap)
  File "<string>", line 13, in <module>



[2019-08-29 10:16:09] Traceback (most recent call last):
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 700, in _apply_rule
    setattr(widget_set, key, value)
  File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
  File "kivy\properties.pyx", line 497, in kivy.properties.Property.__set__
  File "kivy\properties.pyx", line 544, in kivy.properties.Property.set
  File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
  File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1096, in kivy._event.EventObservers._dispatch
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 73, in call_fn
    e_value = eval(value, idmap)
  File "<string>", line 13, in <module>
KeyError: 'Next Page'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Chris/OneDrive/tuks/COS 301/capstone/Git/Defendr2/Defendr/src/Interfaces_v2/main.py", line 98, in <module>
    LoginApp().run()
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\app.py", line 829, in run
    root = self.build()
  File "C:/Users/Chris/OneDrive/tuks/COS 301/capstone/Git/Defendr2/Defendr/src/Interfaces_v2/main.py", line 57, in build
    self.manager.add_widget(Logs_Window(name='logs_window'))
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\relativelayout.py", line 265, in __init__
    super(RelativeLayout, self).__init__(**kw)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\floatlayout.py", line 65, in __init__
    super(FloatLayout, self).__init__(**kwargs)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
    super(Layout, self).__init__(**kwargs)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\widget.py", line 361, in __init__
    rule_children=rule_children)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\widget.py", line 469, in apply_class_lang_rules
    rule_children=rule_children)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 538, in apply
    rule_children=rule_children)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 707, in _apply_rule
    e), cause=tb)
kivy.lang.builder.BuilderException: Parser: File "C:\Users\Chris\OneDrive\tuks\COS 301\capstone\Git\Defendr2\Defendr\src\Interfaces_v2\logs_window.kv", line 50:
...
     48:                    size_hint_x: None
     49:                    width: '50dp'
>>   50:                    icon: 'Next Page'
     51:                    on_press: root.next_pages(log_table)
     52:            BoxLayout:
...
KeyError: 'Next Page'
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 700, in _apply_rule
    setattr(widget_set, key, value)
  File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
  File "kivy\properties.pyx", line 497, in kivy.properties.Property.__set__
  File "kivy\properties.pyx", line 544, in kivy.properties.Property.set
  File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
  File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1096, in kivy._event.EventObservers._dispatch
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 73, in call_fn
    e_value = eval(value, idmap)
  File "<string>", line 13, in <module>



[2019-08-29 10:16:53] Traceback (most recent call last):
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 700, in _apply_rule
    setattr(widget_set, key, value)
  File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
  File "kivy\properties.pyx", line 497, in kivy.properties.Property.__set__
  File "kivy\properties.pyx", line 544, in kivy.properties.Property.set
  File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
  File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1096, in kivy._event.EventObservers._dispatch
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 73, in call_fn
    e_value = eval(value, idmap)
  File "<string>", line 13, in <module>
KeyError: 'Next Page'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Chris/OneDrive/tuks/COS 301/capstone/Git/Defendr2/Defendr/src/Interfaces_v2/main.py", line 98, in <module>
    LoginApp().run()
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\app.py", line 829, in run
    root = self.build()
  File "C:/Users/Chris/OneDrive/tuks/COS 301/capstone/Git/Defendr2/Defendr/src/Interfaces_v2/main.py", line 57, in build
    self.manager.add_widget(Logs_Window(name='logs_window'))
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\relativelayout.py", line 265, in __init__
    super(RelativeLayout, self).__init__(**kw)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\floatlayout.py", line 65, in __init__
    super(FloatLayout, self).__init__(**kwargs)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
    super(Layout, self).__init__(**kwargs)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\widget.py", line 361, in __init__
    rule_children=rule_children)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\widget.py", line 469, in apply_class_lang_rules
    rule_children=rule_children)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 538, in apply
    rule_children=rule_children)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 707, in _apply_rule
    e), cause=tb)
kivy.lang.builder.BuilderException: Parser: File "C:\Users\Chris\OneDrive\tuks\COS 301\capstone\Git\Defendr2\Defendr\src\Interfaces_v2\logs_window.kv", line 39:
...
     37:                    size_hint_x: None
     38:                    width: '50dp'
>>   39:                    icon: 'Next Page'
     40:                    on_press: root.next_pages(log_table)
     41:            BoxLayout:
...
KeyError: 'Next Page'
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 700, in _apply_rule
    setattr(widget_set, key, value)
  File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
  File "kivy\properties.pyx", line 497, in kivy.properties.Property.__set__
  File "kivy\properties.pyx", line 544, in kivy.properties.Property.set
  File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
  File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1096, in kivy._event.EventObservers._dispatch
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 73, in call_fn
    e_value = eval(value, idmap)
  File "<string>", line 13, in <module>



[2019-08-29 10:18:32] Traceback (most recent call last):
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 700, in _apply_rule
    setattr(widget_set, key, value)
  File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
  File "kivy\properties.pyx", line 497, in kivy.properties.Property.__set__
  File "kivy\properties.pyx", line 544, in kivy.properties.Property.set
  File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
  File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1096, in kivy._event.EventObservers._dispatch
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 73, in call_fn
    e_value = eval(value, idmap)
  File "<string>", line 13, in <module>
KeyError: 'next'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Chris/OneDrive/tuks/COS 301/capstone/Git/Defendr2/Defendr/src/Interfaces_v2/main.py", line 98, in <module>
    LoginApp().run()
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\app.py", line 829, in run
    root = self.build()
  File "C:/Users/Chris/OneDrive/tuks/COS 301/capstone/Git/Defendr2/Defendr/src/Interfaces_v2/main.py", line 57, in build
    self.manager.add_widget(Logs_Window(name='logs_window'))
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\relativelayout.py", line 265, in __init__
    super(RelativeLayout, self).__init__(**kw)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\floatlayout.py", line 65, in __init__
    super(FloatLayout, self).__init__(**kwargs)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
    super(Layout, self).__init__(**kwargs)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\widget.py", line 361, in __init__
    rule_children=rule_children)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\widget.py", line 469, in apply_class_lang_rules
    rule_children=rule_children)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 538, in apply
    rule_children=rule_children)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 707, in _apply_rule
    e), cause=tb)
kivy.lang.builder.BuilderException: Parser: File "C:\Users\Chris\OneDrive\tuks\COS 301\capstone\Git\Defendr2\Defendr\src\Interfaces_v2\logs_window.kv", line 48:
...
     46:                    size_hint_x: None
     47:                    width: '50dp'
>>   48:                    icon: 'next'
     49:                    on_press: root.next_pages(log_table)
     50:            BoxLayout:
...
KeyError: 'next'
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 700, in _apply_rule
    setattr(widget_set, key, value)
  File "kivy\weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
  File "kivy\properties.pyx", line 497, in kivy.properties.Property.__set__
  File "kivy\properties.pyx", line 544, in kivy.properties.Property.set
  File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
  File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1096, in kivy._event.EventObservers._dispatch
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 73, in call_fn
    e_value = eval(value, idmap)
  File "<string>", line 13, in <module>

=======
[2019-08-23 15:57:02] Traceback (most recent call last):
  File "main.py", line 98, in <module>
    LoginApp().run()
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/app.py", line 950, in run
    runTouchApp()
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/base.py", line 560, in runTouchApp
    EventLoop.mainloop()
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/base.py", line 334, in mainloop
    self.idle()
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/base.py", line 378, in idle
    self.dispatch_input()
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/base.py", line 329, in dispatch_input
    post_dispatch_input(*pop(0))
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/base.py", line 235, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 1407, in on_motion
    self.dispatch('on_touch_down', me)
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 1423, in on_touch_down
    if w.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/screenmanager.py", line 1193, in on_touch_down
    return super(ScreenManager, self).on_touch_down(touch)
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 545, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/relativelayout.py", line 297, in on_touch_down
    ret = super(RelativeLayout, self).on_touch_down(touch)
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 545, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 545, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 545, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 545, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 545, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 545, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 545, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 545, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/behaviors/button.py", line 151, in on_touch_down
    self.dispatch('on_press')
  File "kivy/_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
  File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
  File "kivy/_event.pyx", line 1132, in kivy._event.EventObservers._dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/lang/builder.py", line 57, in custom_callback
    exec(__kvlang__.co_value, idmap)
  File "/home/darknites/Documents/master/Defendr/src/Interfaces_v2/blacklist_window.kv", line 67, in <module>
    on_press: root.remove_IP(txt_ip_addr.text)
  File "/home/darknites/Documents/master/Defendr/src/Interfaces_v2/blacklist_window.py", line 33, in remove_IP
    app.remove_black_ip(ip_addr)
AttributeError: 'LoginApp' object has no attribute 'remove_black_ip'


[2019-08-23 16:06:12] Traceback (most recent call last):
  File "main.py", line 98, in <module>
    LoginApp().run()
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/app.py", line 951, in run
    self.stop()
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/app.py", line 971, in stop
    self.dispatch('on_stop')
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "main.py", line 48, in on_stop
    Metrics.stop()
  File "/home/darknites/Documents/master/Defendr/src/Interfaces_v2/Metrics.py", line 60, in stop
    thread.stop()
AttributeError: 'Thread' object has no attribute 'stop'


[2019-08-23 16:48:15] Traceback (most recent call last):
  File "main.py", line 98, in <module>
    LoginApp().run()
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/app.py", line 950, in run
    runTouchApp()
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/base.py", line 560, in runTouchApp
    EventLoop.mainloop()
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/base.py", line 334, in mainloop
    self.idle()
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/base.py", line 378, in idle
    self.dispatch_input()
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/base.py", line 329, in dispatch_input
    post_dispatch_input(*pop(0))
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/base.py", line 235, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 1407, in on_motion
    self.dispatch('on_touch_down', me)
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/core/window/__init__.py", line 1423, in on_touch_down
    if w.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/screenmanager.py", line 1193, in on_touch_down
    return super(ScreenManager, self).on_touch_down(touch)
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 545, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/relativelayout.py", line 297, in on_touch_down
    ret = super(RelativeLayout, self).on_touch_down(touch)
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 545, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 545, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 545, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 545, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 545, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/widget.py", line 545, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/uix/behaviors/button.py", line 151, in on_touch_down
    self.dispatch('on_press')
  File "kivy/_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
  File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
  File "kivy/_event.pyx", line 1132, in kivy._event.EventObservers._dispatch
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/lang/builder.py", line 57, in custom_callback
    exec(__kvlang__.co_value, idmap)
  File "/home/darknites/Documents/master/Defendr/src/Interfaces_v2/register.kv", line 138, in <module>
    on_press: root.do_go_to_login(name.text,surname.text,email.text,password.text,confirm_pass.text)
  File "/home/darknites/Documents/master/Defendr/src/Interfaces_v2/register.py", line 14, in do_go_to_login
    output=facade.register(name,surname,email,password,confirm_pass)
  File "/home/darknites/Documents/master/Defendr/src/Interfaces_v2/Facade.py", line 75, in register
    if (not self.database.print_user(self.db_connects)):
TypeError: print_user() missing 1 required positional argument: 'name'


[2019-08-23 17:13:24] Traceback (most recent call last):
  File "main.py", line 98, in <module>
    LoginApp().run()
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/app.py", line 951, in run
    self.stop()
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/app.py", line 971, in stop
    self.dispatch('on_stop')
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "main.py", line 48, in on_stop
    Metrics.stop()
  File "/home/darknites/Documents/master/Defendr/src/Interfaces_v2/Metrics.py", line 60, in stop
    thread.stop()
AttributeError: 'Thread' object has no attribute 'stop'


[2019-08-26 13:30:27] Traceback (most recent call last):
  File "main.py", line 98, in <module>
    LoginApp().run()
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/app.py", line 951, in run
    self.stop()
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/app.py", line 971, in stop
    self.dispatch('on_stop')
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "main.py", line 48, in on_stop
    Metrics.stop()
  File "/home/darknites/shared/Defendr/src/Interfaces_v2/Metrics.py", line 60, in stop
    thread.stop()
AttributeError: 'Thread' object has no attribute 'stop'


[2019-08-26 19:23:55] Traceback (most recent call last):
  File "main.py", line 98, in <module>
    LoginApp().run()
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/app.py", line 951, in run
    self.stop()
  File "/home/darknites/.local/lib/python3.6/site-packages/kivy/app.py", line 971, in stop
    self.dispatch('on_stop')
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "main.py", line 48, in on_stop
    Metrics.stop()
  File "/home/darknites/shared/Defendr/src/Interfaces_v2/Metrics.py", line 60, in stop
    thread.stop()
AttributeError: 'Thread' object has no attribute 'stop'
>>>>>>> development


[2019-10-10 12:28:32] Traceback (most recent call last):
  File "main.py", line 98, in <module>
    LoginApp().run()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 856, in run
    self.stop()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 864, in stop
    self.dispatch('on_stop')
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "main.py", line 48, in on_stop
    Metrics.stop()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/Metrics.py", line 64, in stop
    thread.stop()
AttributeError: 'str' object has no attribute 'stop'


[2019-10-10 12:29:30] Traceback (most recent call last):
  File "main.py", line 98, in <module>
    LoginApp().run()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 856, in run
    self.stop()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 864, in stop
    self.dispatch('on_stop')
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "main.py", line 48, in on_stop
    Metrics.stop()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/Metrics.py", line 64, in stop
    thread.stop()
AttributeError: 'str' object has no attribute 'stop'


[2019-10-10 12:50:29] Traceback (most recent call last):
  File "main.py", line 98, in <module>
    LoginApp().run()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 856, in run
    self.stop()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 864, in stop
    self.dispatch('on_stop')
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "main.py", line 48, in on_stop
    Metrics.stop()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/Metrics.py", line 64, in stop
    thread.stop()
AttributeError: 'str' object has no attribute 'stop'


[2019-10-10 12:56:03] Traceback (most recent call last):
  File "main.py", line 98, in <module>
    LoginApp().run()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 856, in run
    self.stop()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 864, in stop
    self.dispatch('on_stop')
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "main.py", line 48, in on_stop
    Metrics.stop()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/Metrics.py", line 64, in stop
    thread.stop()
AttributeError: 'str' object has no attribute 'stop'


[2019-10-10 13:13:41] Traceback (most recent call last):
  File "main.py", line 98, in <module>
    LoginApp().run()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 856, in run
    self.stop()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 864, in stop
    self.dispatch('on_stop')
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "main.py", line 48, in on_stop
    Metrics.stop()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/Metrics.py", line 64, in stop
    thread.stop()
AttributeError: 'str' object has no attribute 'stop'

